### ISSUE TITLE
Applicants don't receive confirmation emails

### ISSUE THREAD

**Issue by williln** [DjangoGirls/djangogirls#100]
Tina, another organizer in Slack, reported that she submitted a test app and didn't receive a confirmation email. I also submitted a test app and didn't get a confirmation email, and asked an applicant who emailed to confirm that her app submitted whether she received one. She did not. 

So it seems the "confirmation email" functionality mentioned in the [organizer's manual](http://organize.djangogirls.org/attendees/index.html) isn't working. :cry:

**Comment by olasitarska** [comment]
Ah, that's because we moved from Heroku to PythonAnywhere on Sunday. I'll fix the api keys today.

**Comment by williln** [comment]
@olasitarska I just tried to use the messaging component of the application to send an email, and it failed for all the recipients. I assume that's the same issue?

**Comment by olasitarska** [comment]
@williln yeap, same thing. I think I fixed it, could you try now?

**Comment by williln** [comment]
@olasitarska The emails still fail. I don't get any error message, but there are no "Successfully sent emails," all emails are listed under "Emails that failed to send."

**Comment by olasitarska** [comment]
Ok, I fixed one more thing, and tested it -- I received both confirmation of application and e-mail from messaging component. Could you please try again and test yourself? Sorry to bother you! :tulip:

**Comment by williln** [comment]
Still nothing from the messaging component for me :-/ All the email addresses listed as failed. I submitted a test app, so my email address is also included, and I'm not receiving an email. 

It's not a big deal at the moment-- I wasn't sending out an email that can't wait.

**Comment by olasitarska** [comment]
The weirdest thing ever. I'll investigate :)

**Comment by hawkowl** [comment]
Yeah, I didn't get any emails right now (doing DjangoGirls Brisbane). Should I just fall back to manual emails for now?

**Comment by olasitarska** [comment]
I fixed the issue now! :spaghetti:

**Comment by williln** [comment]
Thanks @olasitarska! :lollipop: :bouquet:
